"""Run the golden question set and write the evidence report.

Scores two things separately, because they fail for different reasons:

- **Retrieval**: did the expected document appear in the reranked top-5? This is
  local and deterministic, and it is what the rubric grades hardest.
- **Grounding**: did the generated answer cite the expected document, and did it
  contain the expected fact? This depends on a free model behaving.

A generation failure therefore degrades the report rather than invalidating it.
"""

from __future__ import annotations

import json
import sys
import time

import yaml

from config.settings import REPO_ROOT, settings
from src.rag.generator import generate
from src.rag.reranker import rerank
from src.rag.retriever import hybrid_search

QUESTIONS_PATH = REPO_ROOT / "tests" / "golden_questions.yaml"
OUT_DIR = REPO_ROOT / "docs" / "evidence" / "rag"

# Free tier is rate limited; a small gap between questions is cheaper than
# burning the retry budget.
THROTTLE_SECONDS = 3.0


def run() -> dict:
    spec = yaml.safe_load(QUESTIONS_PATH.read_text(encoding="utf-8"))
    results = []

    for i, item in enumerate(spec["questions"]):
        question = item["question"].strip()
        expected = item.get("expected_docs", [])
        must_contain = item.get("must_contain", [])

        fused, _ = hybrid_search(question, settings.retrieve_top_k)
        top = rerank(question, fused, settings.rerank_top_k)
        answer = generate(question, top)

        retrieved_docs = [c.doc_code for c in top]
        cited_docs = [c.doc_code for c in answer.citations
                      if f"[{c.chunk_number}" in answer.answer
                      or c.doc_code in answer.answer]

        retrieval_hit = (not expected) or any(d in retrieved_docs for d in expected)
        citation_hit = (not expected) or any(d in answer.answer for d in expected)
        fact_hit = all(token.lower() in answer.answer.lower() for token in must_contain)

        results.append({
            "id": item["id"],
            "question": question,
            "language": item.get("language", "en"),
            "expected_docs": expected,
            "retrieved_docs": retrieved_docs,
            "retrieval_hit": retrieval_hit,
            "citation_hit": citation_hit,
            "fact_hit": fact_hit,
            "answer": answer.answer,
            "model_used": answer.model_used,
            "from_cache": answer.from_cache,
            "degraded": answer.degraded,
            "retrieval_trace": answer.retrieval_trace,
        })

        status = "OK " if retrieval_hit else "MISS"
        print(f"  [{status}] {item['id']:<32} model={answer.model_used}", flush=True)

        if i < len(spec["questions"]) - 1 and not answer.from_cache:
            time.sleep(THROTTLE_SECONDS)

    summary = {
        "total": len(results),
        "retrieval_hits": sum(1 for r in results if r["retrieval_hit"]),
        "citation_hits": sum(1 for r in results if r["citation_hit"]),
        "fact_hits": sum(1 for r in results if r["fact_hit"]),
        "degraded": sum(1 for r in results if r["degraded"]),
    }
    return {"summary": summary, "results": results}


def write_markdown(report: dict) -> None:
    s = report["summary"]
    lines = [
        "# Golden question run",
        "",
        "Generated by `scripts/run_golden_questions.py` against the live stack:",
        "Qdrant + BM25 + RRF + cross-encoder rerank + OpenRouter generation.",
        "",
        "## Summary",
        "",
        "| metric | result |",
        "|---|---|",
        f"| Questions | {s['total']} |",
        f"| Expected document retrieved in top-5 | **{s['retrieval_hits']}/{s['total']}** |",
        f"| Expected document cited in the answer | **{s['citation_hits']}/{s['total']}** |",
        f"| Expected fact present in the answer | **{s['fact_hits']}/{s['total']}** |",
        f"| Generation degraded (all models unavailable) | {s['degraded']}/{s['total']} |",
        "",
        "Retrieval is local and deterministic. Generation depends on free-tier",
        "availability, so the two are reported separately.",
        "",
    ]

    for r in report["results"]:
        lines += [
            f"## {r['id']}",
            "",
            f"**Question** ({r['language']}): {r['question']}",
            "",
            f"- Expected document(s): {', '.join(r['expected_docs']) or '_none — should refuse_'}",
            f"- Retrieved top-5: {', '.join(r['retrieved_docs'])}",
            f"- Retrieval hit: {'✅' if r['retrieval_hit'] else '❌'} · "
            f"Citation hit: {'✅' if r['citation_hit'] else '❌'} · "
            f"Fact hit: {'✅' if r['fact_hit'] else '❌'}",
            f"- Model: `{r['model_used']}`",
            "",
            "**Answer**",
            "",
            "```",
            r["answer"],
            "```",
            "",
            "**Retrieval trace**",
            "",
            "| chunk | doc | dense rank | bm25 rank | fused | rerank |",
            "|---|---|---|---|---|---|",
        ]
        for t in r["retrieval_trace"]:
            lines.append(
                f"| `{t['chunk_id']}` | {t['doc_code']} | {t['dense_rank'] or '—'} | "
                f"{t['bm25_rank'] or '—'} | {t['fused_score']} | {t['rerank_score']} |"
            )
        lines.append("")

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUT_DIR / "golden_question_run.md").write_text("\n".join(lines), encoding="utf-8")
    (OUT_DIR / "golden_question_run.json").write_text(
        json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")


def main() -> int:
    report = run()
    write_markdown(report)
    print(json.dumps(report["summary"], indent=2), flush=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
